# coding: utf-8
# NOTE: Auto-generated by OpenAPI Generator — do not edit manually.

from datetime import date, datetime

from flask.json.provider import DefaultJSONProvider

from openapi_server.models.base_model import Model


class JSONEncoder(DefaultJSONProvider):
    include_nulls = False

    def default(self, o):
        if isinstance(o, Model):
            dikt = {}
            for attr in o.openapi_types:
                value = getattr(o, attr)
                if value is None and not self.include_nulls:
                    continue
                attr = o.attribute_map.get(attr, attr)
                dikt[attr] = value
            return dikt
        if isinstance(o, (datetime, date)):
            return o.isoformat()
        return super().default(o)
