# coding: utf-8
# NOTE: Auto-generated by OpenAPI Generator — do not edit manually.

import sys
import typing


def get_type_hints(obj):
    """Wrapper around typing.get_type_hints for older Python versions."""
    try:
        return typing.get_type_hints(obj)
    except Exception:
        return {}


if sys.version_info >= (3, 9):
    from typing import get_args, get_origin
else:
    def get_origin(tp):
        return getattr(tp, "__origin__", None)

    def get_args(tp):
        return getattr(tp, "__args__", ())
