# coding: utf-8
# NOTE: Auto-generated by OpenAPI Generator — do not edit manually.

import datetime
import re
import typing

import six


def _deserialize(data, klass):
    """Deserializes dict, list, str into an object."""
    if data is None:
        return None
    if klass in six.integer_types or klass in (float, str, bool, bytearray):
        return _deserialize_primitive(data, klass)
    if klass == object:
        return _deserialize_object(data)
    if klass == datetime.date:
        return deserialize_date(data)
    if klass == datetime.datetime:
        return deserialize_datetime(data)
    if typing.get_origin(klass) is list:
        return _deserialize_list(data, typing.get_args(klass)[0])
    if typing.get_origin(klass) is dict:
        return _deserialize_dict(data, typing.get_args(klass)[1])
    return deserialize_model(data, klass)


def _deserialize_primitive(data, klass):
    try:
        return klass(data)
    except (UnicodeEncodeError, TypeError):
        return data


def _deserialize_object(value):
    return value


def deserialize_date(string):
    if isinstance(string, datetime.date):
        return string
    try:
        from dateutil.parser import parse
        return parse(string).date()
    except ImportError:
        return datetime.datetime.strptime(string, "%Y-%m-%d").date()


def deserialize_datetime(string):
    if isinstance(string, datetime.datetime):
        return string
    try:
        from dateutil.parser import parse
        return parse(string)
    except ImportError:
        return datetime.datetime.strptime(string, "%Y-%m-%dT%H:%M:%S.%fZ")


def deserialize_model(data, klass):
    if not klass.openapi_types:
        return data
    instance = klass()
    if not isinstance(data, dict):
        return data
    for attr, attr_type in klass.openapi_types.items():
        mapped_key = klass.attribute_map.get(attr, attr)
        if mapped_key in data:
            value = data[mapped_key]
            setattr(instance, attr, _deserialize(value, attr_type))
    return instance


def _deserialize_list(data, boxed_type):
    return [_deserialize(sub_data, boxed_type) for sub_data in data]


def _deserialize_dict(data, boxed_type):
    return {k: _deserialize(v, boxed_type) for k, v in six.iteritems(data)}
