#!/bin/bash
# NOTE: Auto-generated by OpenAPI Generator — do not edit manually.

git init
git add .
git commit -am "Initial commit — Product Management API (openapi-generator python-flask)"
git remote add origin "$1"
git push -u origin main
