[tox]
envlist = py311

[testenv]
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
commands =
    pytest openapi_server/test \
        --cov=openapi_server \
        --cov-report=term-missing \
        --cov-report=html:htmlcov \
        -v

[pytest]
testpaths = openapi_server/test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
