# coding: utf-8
# NOTE: Auto-generated by OpenAPI Generator — do not edit manually.

import pprint
import re
import six
from openapi_server.typing_utils import get_origin, get_args


class Model:
    """Base class for all OpenAPI models."""

    openapi_types: dict = {}
    attribute_map: dict = {}

    @classmethod
    def from_dict(cls, dikt) -> "Model":
        return openapi_server.util.deserialize_model(dikt, cls)  # noqa

    def to_dict(self):
        result = {}
        for attr in self.openapi_types:
            value = getattr(self, attr)
            if value is None:
                continue
            if isinstance(value, list):
                result[attr] = [
                    v.to_dict() if hasattr(v, "to_dict") else v for v in value
                ]
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = {
                    k: v.to_dict() if hasattr(v, "to_dict") else v
                    for k, v in value.items()
                }
            else:
                result[attr] = value
        return result

    def to_str(self):
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        return self.to_str()

    def __eq__(self, other):
        if not isinstance(other, Model):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
