# coding: utf-8
# NOTE: Auto-generated by OpenAPI Generator — do not edit manually.

from __future__ import absolute_import
from typing import List, Optional

from openapi_server.models.base_model import Model


class FieldError(Model):
    openapi_types = {"field": str, "message": str}
    attribute_map = {"field": "field", "message": "message"}

    def __init__(self, field: Optional[str] = None, message: Optional[str] = None):
        self._field = field
        self._message = message

    @property
    def field(self) -> Optional[str]:
        return self._field

    @field.setter
    def field(self, value: Optional[str]):
        self._field = value

    @property
    def message(self) -> Optional[str]:
        return self._message

    @message.setter
    def message(self, value: Optional[str]):
        self._message = value


class ErrorResponse(Model):
    openapi_types = {
        "success": bool,
        "message": str,
        "errors": List[FieldError],
    }
    attribute_map = {
        "success": "success",
        "message": "message",
        "errors": "errors",
    }

    def __init__(
        self,
        success: bool = False,
        message: Optional[str] = None,
        errors: Optional[List[FieldError]] = None,
    ):
        self._success = success
        self._message = message
        self._errors = errors or []

    @property
    def success(self) -> bool:
        return self._success

    @success.setter
    def success(self, value: bool):
        self._success = value

    @property
    def message(self) -> Optional[str]:
        return self._message

    @message.setter
    def message(self, value: Optional[str]):
        self._message = value

    @property
    def errors(self) -> List[FieldError]:
        return self._errors

    @errors.setter
    def errors(self, value: List[FieldError]):
        self._errors = value
