# coding: utf-8
# NOTE: Auto-generated by OpenAPI Generator — do not edit manually.

from __future__ import absolute_import
from typing import List, Optional

from openapi_server.models.base_model import Model
from openapi_server.models.product import Product


class Pagination(Model):
    openapi_types = {
        "total": int,
        "page": int,
        "limit": int,
        "total_pages": int,
    }
    attribute_map = {
        "total": "total",
        "page": "page",
        "limit": "limit",
        "total_pages": "total_pages",
    }

    def __init__(self, total: int = 0, page: int = 1, limit: int = 10, total_pages: int = 0):
        self._total = total
        self._page = page
        self._limit = limit
        self._total_pages = total_pages

    @property
    def total(self) -> int:
        return self._total

    @total.setter
    def total(self, value: int):
        self._total = value

    @property
    def page(self) -> int:
        return self._page

    @page.setter
    def page(self, value: int):
        self._page = value

    @property
    def limit(self) -> int:
        return self._limit

    @limit.setter
    def limit(self, value: int):
        self._limit = value

    @property
    def total_pages(self) -> int:
        return self._total_pages

    @total_pages.setter
    def total_pages(self, value: int):
        self._total_pages = value


class ProductListData(Model):
    openapi_types = {
        "products": List[Product],
        "pagination": Pagination,
    }
    attribute_map = {
        "products": "products",
        "pagination": "pagination",
    }

    def __init__(self, products: Optional[List[Product]] = None, pagination: Optional[Pagination] = None):
        self._products = products or []
        self._pagination = pagination

    @property
    def products(self) -> List[Product]:
        return self._products

    @products.setter
    def products(self, value: List[Product]):
        self._products = value

    @property
    def pagination(self) -> Optional[Pagination]:
        return self._pagination

    @pagination.setter
    def pagination(self, value: Optional[Pagination]):
        self._pagination = value


class ProductListResponse(Model):
    openapi_types = {
        "success": bool,
        "data": ProductListData,
    }
    attribute_map = {
        "success": "success",
        "data": "data",
    }

    def __init__(self, success: bool = True, data: Optional[ProductListData] = None):
        self._success = success
        self._data = data

    @property
    def success(self) -> bool:
        return self._success

    @success.setter
    def success(self, value: bool):
        self._success = value

    @property
    def data(self) -> Optional[ProductListData]:
        return self._data

    @data.setter
    def data(self, value: Optional[ProductListData]):
        self._data = value
