# coding: utf-8
# NOTE: Auto-generated by OpenAPI Generator — do not edit manually.

from __future__ import absolute_import
from datetime import datetime
from typing import List, Optional

from openapi_server.models.base_model import Model


class Product(Model):
    """Product model generated from OpenAPI spec."""

    openapi_types = {
        "id": str,
        "name": str,
        "description": str,
        "price": float,
        "category": str,
        "stock": int,
        "image_url": str,
        "is_active": bool,
        "created_at": datetime,
        "updated_at": datetime,
    }

    attribute_map = {
        "id": "id",
        "name": "name",
        "description": "description",
        "price": "price",
        "category": "category",
        "stock": "stock",
        "image_url": "image_url",
        "is_active": "is_active",
        "created_at": "created_at",
        "updated_at": "updated_at",
    }

    CATEGORY_CHOICES = ["Electronics", "Clothing", "Books", "Food", "Sports"]

    def __init__(
        self,
        id: Optional[str] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
        price: Optional[float] = None,
        category: Optional[str] = None,
        stock: int = 0,
        image_url: Optional[str] = None,
        is_active: bool = True,
        created_at: Optional[datetime] = None,
        updated_at: Optional[datetime] = None,
    ):
        self._id = id
        self._name = name
        self._description = description
        self._price = price
        self._category = category
        self._stock = stock
        self._image_url = image_url
        self._is_active = is_active
        self._created_at = created_at
        self._updated_at = updated_at

    # --- id ---
    @property
    def id(self) -> Optional[str]:
        return self._id

    @id.setter
    def id(self, value: Optional[str]):
        self._id = value

    # --- name ---
    @property
    def name(self) -> Optional[str]:
        return self._name

    @name.setter
    def name(self, value: Optional[str]):
        if value is not None and (len(value) < 2 or len(value) > 200):
            raise ValueError("name must be between 2 and 200 characters")
        self._name = value

    # --- description ---
    @property
    def description(self) -> Optional[str]:
        return self._description

    @description.setter
    def description(self, value: Optional[str]):
        self._description = value

    # --- price ---
    @property
    def price(self) -> Optional[float]:
        return self._price

    @price.setter
    def price(self, value: Optional[float]):
        if value is not None and value < 0:
            raise ValueError("price must be >= 0")
        self._price = value

    # --- category ---
    @property
    def category(self) -> Optional[str]:
        return self._category

    @category.setter
    def category(self, value: Optional[str]):
        if value is not None and value not in self.CATEGORY_CHOICES:
            raise ValueError(f"category must be one of {self.CATEGORY_CHOICES}")
        self._category = value

    # --- stock ---
    @property
    def stock(self) -> int:
        return self._stock

    @stock.setter
    def stock(self, value: int):
        if value is not None and value < 0:
            raise ValueError("stock must be >= 0")
        self._stock = value

    # --- image_url ---
    @property
    def image_url(self) -> Optional[str]:
        return self._image_url

    @image_url.setter
    def image_url(self, value: Optional[str]):
        self._image_url = value

    # --- is_active ---
    @property
    def is_active(self) -> bool:
        return self._is_active

    @is_active.setter
    def is_active(self, value: bool):
        self._is_active = value

    # --- created_at ---
    @property
    def created_at(self) -> Optional[datetime]:
        return self._created_at

    @created_at.setter
    def created_at(self, value: Optional[datetime]):
        self._created_at = value

    # --- updated_at ---
    @property
    def updated_at(self) -> Optional[datetime]:
        return self._updated_at

    @updated_at.setter
    def updated_at(self, value: Optional[datetime]):
        self._updated_at = value
